#!/usr/bin/env bash
# Displays DNS A record information for subdomains of a given domain

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    local destination

    record_type=$(dig @8.8.8.8 "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    destination=$(dig @8.8.8.8 "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain="$1"
subdomain="$2"

if [ -n "$subdomain" ]; then
    get_subdomain_info "$domain" "$subdomain"
else
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
fi
